---
HostBusinessName1:
  alias:
    - Host1
    - AltName1
  services:
    port:
      - 10.0.0.4:
          - 111
          - 444
      - hostName: 222
    http:
      - 10.0.0.3:80
      - hostName: 8080
    https:
      - github.com:443

HostBusinessName2:
  alias:
    - Host2
    - AltName2
  services:
    port:
      - 10.0.0.4:
          - 111
          - 444
      - hostName: 222
    pg:
      - clusterName.local:5432

_default_:
  services:
    port:
      - hostName5:
          - 111
          - 444
