_default_:
  services:
    port:
      - 1.1.1.1:
          - 53
          - 444
      - hostName: 222
    pg:
      - clusterName.local: 5432
    http:
      - petstore.swagger.io: 
        - 80
        - 443
        - 8080
      - hostName: 8080
    https:
      - github.com: 443
      - huggingface.co: 
        - 444
        - 80
        - 443
  serviceGroups:         
    db-cluster:          
    Exadata: 


_serviceGroups_:
  db-cluster :
    port:
      - db-master:
          - 5432
          - 5433
      - db-slave: 5432
  Exadata:
    port:
      - db-Exadata: 1251  